routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProvinsiController;
use App\Http\Controllers\KabupatenKotaController;
use App\Http\Controllers\KecamatanController;
use App\Http\Controllers\KelurahanController;
use App\Http\Controllers\ParticipantController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'AuthController@index')->name('login');
// Route::post('post-login', 'AuthController@postLogin')->name('post-login'); 
// Route::get('dashboard', 'AuthController@dashboard')->name('dashboard'); 
// Route::get('logout', 'AuthController@logout');
Route::get('/', 'AuthController@showFormLogin')->name('login');
Route::get('login', 'AuthController@showFormLogin')->name('login');
Route::post('login', 'AuthController@login');
Route::get('register', 'AuthController@showFormRegister')->name('register');
Route::post('register', 'AuthController@register');
 
Route::group(['middleware' => 'auth'], function () {
    Route::get('home', 'AuthController@dashboard')->name('home');
    Route::get('dashboard', 'AuthController@dashboard')->name('dashboard');
    Route::get('logout', 'AuthController@logout')->name('logout');
 	
 	Route::resource('provinsi', 'ProvinsiController');
	Route::resource('kabupaten-kota', 'KabupatenKotaController');
	Route::resource('kecamatan', 'KecamatanController');
	Route::resource('kelurahan', 'KelurahanController');
	Route::resource('participant', 'ParticipantController');

	Route::get('/participant/create/provinsi/{id}', [ParticipantController::class, 'getKabupatenKota']);
	Route::get('/participant/create/kab/{id}', [ParticipantController::class, 'getKecamatan']);
	Route::get('/participant/create/kecamatan/{id}', [ParticipantController::class, 'getKelurahan']);
});

resources/views/pages/kabupaten_kota.blade.php
@extends('layouts.content')

@section('content')
		<!-- Main content -->
		<div class="content-wrapper">
			<!-- Content area -->
			<div class="content">

				<!-- Basic datatable -->
				<div class="card">
					<div class="card-header header-elements-inline">
						<h5 class="card-title">Data Kabupaten/ Kota</h5>
						<div class="header-elements">
							<div class="list-icons">
		                		<a class="list-icons-item" data-action="collapse"></a>
		                		<a class="list-icons-item" data-action="reload"></a>
		                	</div>
	                	</div>
					</div>
					@if(session('success'))
			            <div class="alert alert-success alert-dismissible fade show" role="alert">
			            	<span class="alert-text">{{ session('success') }}</span>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif
			        @if(session('failed'))
			            <div class="alert alert-danger alert-dismissible fade show" role="alert">
			            	<span class="alert-text">{{ session('failed') }}</span>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif

					<div class="card-body">
						<form action="{{route('kabupaten-kota.store')}}" method="POST">
							@csrf
							<fieldset class="mb-0">
								<div class="row">
									<div class="col-lg-3">
										<label class="col-form-label">Provinsi</label>		
									</div>
									<div class="col-lg-3">
										<label class="col-form-label">Kabupaten/ Kota <span class="text-danger font-weight-bold"><i>*<small>Wajib diisi</small></i></span></label>
									</div>
								</div>
								<div class="form-group row">
									<div class="col-lg-3">
										<select class="form-control" name="provinsi_id" id="provinsi_id" required>
											@foreach ($provinsi as $r)
												<option value="{{ $r->id }}">{{ $r->name }}</option>
											@endforeach
										</select>
									</div>
									<div class="col-lg-3">
										<input type="text" class="form-control" name="name" minlength="3" maxlength="255" placeholder="Nama Kabupaten/ Kota" required>
									</div>
									<div class="text-right">
										<button type="submit" class="btn btn-primary">Tambah</button>
									</div>
								</div>
							</fieldset>
						</form>
					</div>
					<table class="table datatable-basic">
						<thead>
							<tr>
								<th>ID</th>
								<th>Nama Kabupaten/ Kota</th>
								<th>Nama Provinsi</th>
								<th class="text-center" colspan="3">Aksi</th>
							</tr>
						</thead>
						<tbody>
							@foreach($kab as $row)
							<tr>
								<td>{{ $row->id }}</td>
								<td>{{ $row->name }}</td>
								<td>{{ $row->provinsi_name }}</td>
								<td></td>
								<td class="text-center">
									<form action="{{ route('kabupaten-kota.destroy', $row->id) }}" method="POST">
										<a href="{{ route('kabupaten-kota.edit', $row->id) }}" class="btn btn-warning"><i class="icon-pencil7"></i> Edit</a>
			                            @csrf
			                            @method('DELETE')
			                            <button type="submit" class="btn btn-danger"><i class="icon-trash-alt"></i> Hapus</button>
			                        </form>
								</td>
								<td></td>
							</tr>
							@endforeach
						</tbody>
					</table>
					<br>
				</div>
				<!-- /basic datatable -->

			</div>
			<!-- /content area -->

@endsection

resources/views/pages/kecamatan-edit.blade.php
@extends('layouts.content')

@section('content')
		<!-- Main content -->
		<div class="content-wrapper">
			<!-- Content area -->
			<div class="content">

				<!-- Basic datatable -->
				<div class="card">
					<div class="card-header header-elements-inline">
						<h5 class="card-title">Edit Data Provinsi</h5>
					</div>

					@if($errors->any())
			            <div class="alert alert-danger alert-dismissible fade show" role="alert">
			            	<strong>Terjadi kesalahan</strong>
			            	<ul>
			            		@foreach($errors->all() as $err)
			            			<li>{{ $err }}</li>
			            		@endforeach
			            	</ul>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif

					<div class="card-body">
						<form action="{{route('kecamatan.update', $kecamatan->id)}}" method="POST">
							@csrf
							@method('PUT')
							<fieldset class="mb-3">
								<div class="form-group row">
									<label class="col-form-label col-lg-2">ID</label>
									<div class="col-lg-3">
										<input type="text" class="form-control" name="id" minlength="1" maxlength="10" value="{{$kecamatan->id}}" readonly>
									</div>
								</div>
								<div class="form-group row">
									<label class="col-form-label col-lg-2">Nama Kabupaten/ Kota <span class="text-danger font-weight-bold">*</span></label>
									<div class="col-lg-3">
										<select class="form-control" name="kabupaten_kota_id" required>
											@foreach ($kab as $r)
												<option value="{{ $r->id }}" <?=($r->id==$kecamatan->kabupaten_kota_id)?'selected':''?>>{{ $r->name }}</option>
											@endforeach
										</select>
									</div>
								</div>
								<div class="form-group row">
									<label class="col-form-label col-lg-2">Nama Kecamatan <span class="text-danger font-weight-bold">*</span></label>
									<div class="col-lg-3">
										<input type="text" class="form-control" name="name" minlength="3" maxlength="255" placeholder="Nama Kecamatan" value="{{$kecamatan->name}}" required>
									</div>
								</div>
								<div class="form-group row">
									<label class="col-form-label col-lg-2 text-danger font-weight-bold"><i>* Wajib diisi</i></label>
								</div>
								<div class="form-group row">
									<div class="col-lg-3">
										<button type="submit" class="btn btn-primary">Update</button>
									</div>
								</div>
							</fieldset>
						</form>
					</div>	
				</div>

			</div>
			<!-- /content area -->

@endsection

resources/views/pages/kecamatan.blade.php
@extends('layouts.content')

@section('content')
		<!-- Main content -->
		<div class="content-wrapper">
			<!-- Content area -->
			<div class="content">

				<!-- Basic datatable -->
				<div class="card">
					<div class="card-header header-elements-inline">
						<h5 class="card-title">Data Kecamatan</h5>
						<div class="header-elements">
							<div class="list-icons">
		                		<a class="list-icons-item" data-action="collapse"></a>
		                		<a class="list-icons-item" data-action="reload"></a>
		                	</div>
	                	</div>
					</div>
					@if(session('success'))
			            <div class="alert alert-success alert-dismissible fade show" role="alert">
			            	<span class="alert-text">{{ session('success') }}</span>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif
			        @if(session('failed'))
			            <div class="alert alert-danger alert-dismissible fade show" role="alert">
			            	<span class="alert-text">{{ session('failed') }}</span>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif

					<div class="card-body">
						<form action="{{route('kecamatan.store')}}" method="POST">
							@csrf
							<fieldset class="mb-0">
								<div class="row">
									<div class="col-lg-3">
										<label class="col-form-label">Kabupaten/ Kota</label>		
									</div>
									<div class="col-lg-3">
										<label class="col-form-label">Kecamatan <span class="text-danger font-weight-bold"><i>*<small>Wajib diisi</small></i></span></label>
									</div>
								</div>
								<div class="form-group row">
									<div class="col-lg-3">
										<select class="form-control" name="kabupaten_kota_id" required>
											@foreach ($kab as $r)
												<option value="{{ $r->id }}">{{ $r->name }}</option>
											@endforeach
										</select>
									</div>
									<div class="col-lg-3">
										<input type="text" class="form-control" name="name" minlength="3" maxlength="255" placeholder="Nama Kecamatan" required>
									</div>
									<div class="text-right">
										<button type="submit" class="btn btn-primary">Tambah</button>
									</div>
								</div>
							</fieldset>
						</form>
					</div>
					<table class="table datatable-basic">
						<thead>
							<tr>
								<th>ID</th>
								<th>Nama Kecamatan</th>
								<th>Nama Kabupaten/ Kota</th>
								<th class="text-center" colspan="3">Aksi</th>
							</tr>
						</thead>
						<tbody>
							@foreach($kecamatan as $row)
							<tr>
								<td>{{ $row->id }}</td>			
								<td>{{ $row->name }}</td>		
								<td>{{ $row->kab_name }}</td>
								<td></td>
								<td class="text-center">
									<form action="{{ route('kecamatan.destroy', $row->id) }}" method="POST">
										<a href="{{ route('kecamatan.edit', $row->id) }}" class="btn btn-warning"><i class="icon-pencil7"></i> Edit</a>
			                            @csrf
			                            @method('DELETE')
			                            <button type="submit" class="btn btn-danger"><i class="icon-trash-alt"></i> Hapus</button>
			                        </form>
								</td>
								<td></td>
							</tr>
							@endforeach
						</tbody>
					</table>
					<br>
				</div>
				<!-- /basic datatable -->

			</div>
			<!-- /content area -->

@endsection

resources/views/pages/kelurahan.blade.php
@extends('layouts.content')

@section('content')
		<!-- Main content -->
		<div class="content-wrapper">
			<!-- Content area -->
			<div class="content">

				<!-- Basic datatable -->
				<div class="card">
					<div class="card-header header-elements-inline">
						<h5 class="card-title">Data Kelurahan</h5>
						<div class="header-elements">
							<div class="list-icons">
		                		<a class="list-icons-item" data-action="collapse"></a>
		                		<a class="list-icons-item" data-action="reload"></a>
		                	</div>
	                	</div>
					</div>
					@if(session('success'))
			            <div class="alert alert-success alert-dismissible fade show" role="alert">
			            	<span class="alert-text">{{ session('success') }}</span>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif
			        @if(session('failed'))
			            <div class="alert alert-danger alert-dismissible fade show" role="alert">
			            	<span class="alert-text">{{ session('failed') }}</span>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif

					<div class="card-body">
						<form action="{{route('kelurahan.store')}}" method="POST">
							@csrf
							<fieldset class="mb-1">
								<div class="row">
									<div class="col-lg-3">
										<label class="col-form-label">Kecamatan</label>		
									</div>
									<div class="col-lg-3">
										<label class="col-form-label">Kelurahan <span class="text-danger font-weight-bold"><i>*<small>Wajib diisi</small></i></span></label>
									</div>
								</div>
								<div class="form-group row">
									<div class="col-lg-3">
										<select class="form-control" name="kecamatan_id" required>
											@foreach ($kecamatan as $r)
												<option value="{{ $r->id }}">{{ $r->name }}</option>
											@endforeach
										</select>
									</div>
									<div class="col-lg-3">
										<input type="text" class="form-control" name="name" minlength="3" maxlength="255" placeholder="Nama Kelurahan" required>
									</div>
									<div class="text-right">
										<button type="submit" class="btn btn-primary">Tambah</button>
									</div>
								</div>
							</fieldset>
						</form>
					</div>
					<table class="table datatable-basic">
						<thead>
							<tr>
								<th>ID</th>
								<th>Nama Kelurahan</th>
								<th>Nama Kecamatan</th>
								<th class="text-center" colspan="3">Aksi</th>
							</tr>
						</thead>
						<tbody>
							@foreach($kelurahan as $row)
							<tr>
								<td>{{ $row->id }}</td>
								<td>{{ $row->name }}</td>
								<td>{{ $row->kecamatan_name }}</td>
								<td></td>
								<td class="text-center">
									<form action="{{ route('kelurahan.destroy', $row->id) }}" method="POST">
										<a href="{{ route('kelurahan.edit', $row->id) }}" class="btn btn-warning"><i class="icon-pencil7"></i> Edit</a>
			                            @csrf
			                            @method('DELETE')
			                            <button type="submit" class="btn btn-danger"><i class="icon-trash-alt"></i> Hapus</button>
			                        </form>
								</td>
								<td></td>
							</tr>
							@endforeach
						</tbody>
					</table>
					<br>
				</div>
				<!-- /basic datatable -->

			</div>
			<!-- /content area -->

@endsection

resources/views/pages/participant-edit.blade.php
@extends('layouts.content')

@section('content')
		<!-- Main content -->
		<div class="content-wrapper">
			<!-- Content area -->
			<div class="content">

				<!-- Basic datatable -->
				<div class="card">
					<div class="card-header header-elements-inline">
						<h5 class="card-title">Detail Data Participant</h5>
					</div>

					@if($errors->any())
			            <div class="alert alert-danger alert-dismissible fade show" role="alert">
			            	<strong>Terjadi kesalahan</strong>
			            	<ul>
			            		@foreach($errors->all() as $err)
			            			<li>{{ $err }}</li>
			            		@endforeach
			            	</ul>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif

					<div class="card-body">
						<form action="{{route('participant.update', $participant->id)}}" method="POST" enctype="multipart/form-data">
							@csrf
							@method('PUT')
							<fieldset class="mb-3">
								<div class="row">
									<div class="col-lg-2 text-center">
										@if ($participant->image == '')
											<img src="{{url('uploads').'/no-image.jpg'}}" class="img-fluid img-thumbnail mb-1"><br>
											<i>Gambar belum diatur</i>
										@else
											<img src="{{url('uploads').'/'.$participant->image}}" class="img-fluid img-thumbnail">
										@endif
									</div>
									<div class="col-lg-10">
										<div class="form-group row">
											<div class="col-lg-2 font-weight-bold">Nama <span class="text-danger font-weight-bold">*</span></div>
											<div class="col-lg-4"> 
												<input type="text" class="form-control" name="name" minlength="3" maxlength="255" placeholder="Nama Participant" value="{{$participant->name}}" required>
											</div>
										</div>
										<div class="form-group row">
											<div class="col-lg-2 font-weight-bold">Email <span class="text-danger font-weight-bold">*</span></div>
											<div class="col-lg-4"> 
												<input type="email" class="form-control" name="email" minlength="10" maxlength="255" placeholder="Nama Provinsi" value="{{$participant->email}}" required>
											</div>
										</div>
										<div class="form-group row">
											<div class="col-lg-2 font-weight-bold">No Telepon <span class="text-danger font-weight-bold">*</span></div>
											<div class="col-lg-4"> 
												<input type="text" class="form-control" name="phone" minlength="8" maxlength="16" placeholder="No telepon" value="{{$participant->phone}}" required>
											</div>
										</div>
										<div class="form-group row">
											<div class="col-lg-2 font-weight-bold">Provinsi</div>
											<div class="col-lg-4"> 
												<select class="form-control" name="provinsi_id">
													<option value="">Pilih Provinsi</option>
													@foreach ($provinsi as $r)
														<option value="{{ $r->id }}" <?=($r->id==$participant->provinsi_id)?'selected':''?>>{{ $r->name }}</option>
													@endforeach
												</select>
											</div>
										</div>
										<div class="form-group row">
											<div class="col-lg-2 font-weight-bold">Kabupaten/ Kota</div>
											<div class="col-lg-4"> 
												<select class="form-control" name="kabupaten_kota_id">
													<option value="">Pilih Kabupaten/ Kota</option>
													@foreach ($kab as $r)
														<option value="{{ $r->id }}" <?=($r->id==$participant->kabupaten_kota_id)?'selected':''?>>{{ $r->name }}</option>
													@endforeach
												</select>
											</div>
											<div id="kab">
												<img src="{{asset('assets/global_assets/images/ajax-loader.gif')}}"> Mohon tunggu sejenak..
											</div>
										</div>
										<div class="form-group row">
											<div class="col-lg-2 font-weight-bold">Kecamatan</div>
											<div class="col-lg-4"> 
												<select class="form-control" name="kecamatan_id">
													<option value="">Pilih Kecamatan</option>
													@foreach ($kecamatan as $r)
														<option value="{{ $r->id }}" <?=($r->id==$participant->kecamatan_id)?'selected':''?>>{{ $r->name }}</option>
													@endforeach
												</select>
											</div>
											<div id="kec">
												<img src="{{asset('assets/global_assets/images/ajax-loader.gif')}}"> Mohon tunggu sejenak..
											</div>
										</div>
										<div class="form-group row">
											<div class="col-lg-2 font-weight-bold">Kelurahan</div>
											<div class="col-lg-4"> 
												<select class="form-control" name="kelurahan_id">
													<option value="">Pilih Kelurahan</option>
													@foreach ($kelurahan as $r)
														<option value="{{ $r->id }}" <?=($r->id==$participant->kelurahan_id)?'selected':''?>>{{ $r->name }}</option>
													@endforeach
												</select>
											</div>
											<div id="kel">
												<img src="{{asset('assets/global_assets/images/ajax-loader.gif')}}"> Mohon tunggu sejenak..
											</div>
										</div>
										<div class="form-group row">
											<div class="col-lg-2 font-weight-bold">Foto</div>
											<div class="col-lg-4"> 
												<input type="file" class="form-control" name="image" accept="image/*">
											</div>
										</div>
										<div class="form-group row">
											<label class="col-form-label col-lg-2 text-danger font-weight-bold"><i>* Wajib diisi</i></label>
										</div>
										<div class="form-group row">
											<div class="col-lg-6">
												<button type="submit" class="btn btn-primary">Update</button>
												<a class="btn btn-warning" href="{{ route('participant.index') }}">Cancel</a>
											</div>
										</div>
									</div>
								</div>
							</fieldset>
						</form>
					</div>	
				</div>

			</div>
			<!-- /content area -->

@endsection

@section('script')
	<script type="text/javascript">
		$(document).ready(function(){
			$('#kab').hide();
			$('#kec').hide();
			$('#kel').hide();
			$('select[name="provinsi_id"]').on('change', function() {
	            var provinsi = $(this).val();
	            $('#kab').show();
	            if(provinsi) {
	                $.ajax({
	                    url: "{{ url('/participant/create/provinsi') }}"+'/'+provinsi,
	                    type: "GET",
	                    dataType: "json",
	                    success:function(data) {
	                        $('select[name="kabupaten_kota_id"]').empty();
	                        $.each(data, function(i, item) {
	                            $('select[name="kabupaten_kota_id"]').append('<option value="'+ data[i].id +'">'+ data[i].name +'</option>');
	                        });
	                    },
	                    complete: function () { 
			                $('#kab').hide();
			            }
	                });
	            }else{
	                $('select[name="kabupaten_kota_id"]').empty();
	            }
        	});


        	$('select[name="kabupaten_kota_id"]').on('click', function() {
	            var kab = $(this).val();
	            $('#kec').show();
	            if(kab) {
	                $.ajax({
	                    url: "{{ url('/participant/create/kab') }}"+'/'+kab,
	                    type: "GET",
	                    dataType: "json",
	                    success:function(data) {
	                        $('select[name="kecamatan_id"]').empty();
	                        $.each(data, function(i, item) {
	                            $('select[name="kecamatan_id"]').append('<option value="'+ data[i].id +'">'+ data[i].name +'</option>');
	                        });
	                    },
	                    complete: function () { 
			                $('#kec').hide();
			            }
	                });
	            }else{
	                $('select[name="kecamatan_id"]').empty();
	            }
        	});

        	$('select[name="kecamatan_id"]').on('click', function() {
	            var kecamatan = $(this).val();
	            $('#kel').show();
	            if(kecamatan) {
	                $.ajax({
	                    url: "{{ url('/participant/create/kecamatan') }}"+'/'+kecamatan,
	                    type: "GET",
	                    dataType: "json",
	                    success:function(data) {
	                        $('select[name="kelurahan_id"]').empty();
	                        $.each(data, function(i, item) {
	                            $('select[name="kelurahan_id"]').append('<option value="'+ data[i].id +'">'+ data[i].name +'</option>');
	                        });
	                    },
	                    complete: function () { 
			                $('#kel').hide();
			            }
	                });
	            }else{
	                $('select[name="kelurahan_id"]').empty();
	            }
        	});
    	});
	</script>
@endsection

resources/views/pages/participant.blade.php
@extends('layouts.content')

@section('content')
		<!-- Main content -->
		<div class="content-wrapper">
			<!-- Content area -->
			<div class="content">

				<!-- Basic datatable -->
				<div class="card">
					<div class="card-header header-elements-inline">
						<h5 class="card-title">Data Participant</h5>
						<div class="header-elements">
							<div class="list-icons">
		                		<a class="list-icons-item" data-action="collapse"></a>
		                		<a class="list-icons-item" data-action="reload"></a>
		                	</div>
	                	</div>
					</div>

					@if(session('failed'))
			            <div class="alert alert-danger alert-dismissible fade show" role="alert">
			            	<span class="alert-text">{{ session('failed') }}</span>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif

					<div class="card-body">
						<a href="{{ route('participant.create') }}" class="btn btn-info">Tambah Data</a>
					</div>
					<table class="table datatable-basic">
						<thead>
							<tr>
								<th>Nama</th>
								<th>Email</th>
								<th>Phone</th>
								<th class="text-center" colspan="3">Aksi</th>
							</tr>
						</thead>
						<tbody>
							@foreach($participant as $row)
								<tr>
									<td>{{ $row->name }}</td>
									<td>{{ $row->email }}</td>
									<td>{{ $row->phone }}</td>
									<td></td>
									<td class="text-center">
										<form action="{{ route('participant.destroy', $row->id) }}" method="POST">
											<a href="{{ route('participant.show', $row->id) }}" class="btn btn-sm btn-info"><i class="icon-eye"></i> Detail</a>
											<a href="{{ route('participant.edit', $row->id) }}" class="btn btn-sm btn-warning"><i class="icon-pencil7"></i> Edit</a>
				                            @csrf
				                            @method('DELETE')
				                            <button type="submit" class="btn btn-sm btn-danger"><i class="icon-trash-alt"></i> Hapus</button>
				                        </form>
									</td>
									<td></td>
								</tr>
							@endforeach
						</tbody>
					</table>
					<br>
				</div>
				<!-- /basic datatable -->

			</div>
			<!-- /content area -->

@endsection

resources/views/pages/provinsi.blade.php
@extends('layouts.content')

@section('content')
		<!-- Main content -->
		<div class="content-wrapper">
			<!-- Content area -->
			<div class="content">

				<!-- Basic datatable -->
				<div class="card">
					<div class="card-header header-elements-inline">
						<h5 class="card-title">Data Provinsi</h5>
						<div class="header-elements">
							<div class="list-icons">
		                		<a class="list-icons-item" data-action="collapse"></a>
		                		<a class="list-icons-item" data-action="reload"></a>
		                	</div>
	                	</div>
					</div>

					@if(session('success'))
			            <div class="alert alert-success alert-dismissible fade show" role="alert">
			            	<span class="alert-text">{{ session('success') }}</span>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif
			        @if(session('failed'))
			            <div class="alert alert-danger alert-dismissible fade show" role="alert">
			            	<span class="alert-text">{{ session('failed') }}</span>
			            	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			                	<span aria-hidden="true">&times;</span>
			            	</button>
			            </div>
			        @endif

					<div class="card-body">
						<form action="{{route('provinsi.store')}}" method="POST">
							@csrf
							<fieldset class="mb-0">
								<div class="form-group row">
									<div class="col-lg-3">
										<input type="text" class="form-control" name="name" minlength="3" maxlength="255" placeholder="Nama Provinsi" required>
									</div>
									<div class="text-right">
										<button type="submit" class="btn btn-primary">Tambah</button>
									</div>
								</div>
							</fieldset>
						</form>
					</div>
					<table class="table datatable-basic">
						<thead>
							<tr>
								<th>ID</th>
								<th>Nama Provinsi</th>
								<th class="text-center" colspan="4">Aksi</th>
							</tr>
						</thead>
						<tbody>
							@foreach($provinsi as $row)
							<tr>
								<td>{{ $row->id }}</td>
								<td>{{ $row->name }}</td>
								<td></td>
								<td class="text-center">
									<form action="{{ route('provinsi.destroy', $row->id) }}" method="POST">
										<a href="{{ route('provinsi.edit', $row->id) }}" class="btn btn-warning"><i class="icon-pencil7"></i> Edit</a>
			                            @csrf
			                            @method('DELETE')
			                            <button type="submit" class="btn btn-danger"><i class="icon-trash-alt"></i> Hapus</button>
			                        </form>
								</td>
								<td></td>
								<td></td>
							</tr>
							@endforeach
						</tbody>
					</table>
					<br>
				</div>
				<!-- /basic datatable -->

			</div>
			<!-- /content area -->

@endsection